version: '3.8'

services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"  # Expose the Spring Boot API on port 8080
        depends_on:
            - memcached

    memcached:
        image: memcached:latest
        ports:
            - "11211:11211"  # Expose Memcached on port 11211
